name: flutter_switch_2_3_states
description: Widget switch with 2 or 3 states and custom icons, values and text
version: 0.0.2
homepage: https://github.com/robertoltrocha

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dart_style: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: