name: flutter_switch_2_3_states
description: Widget switch with 2 or 3 states and custom icons, values and text.
version: 0.0.8
homepage: https://github.com/robertoltrocha/flutter_switch_2_3_states
issue_tracker: https://github.com/robertoltrocha/flutter_switch_2_3_states/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: